### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/euro-calliope#103]
Initial tasks:

* [x] Create minimal sphinx documentation #106
* [x] Add background on the purpose #107 (also see: Clarify purpose and naming #105)
* [x] Add overview of repository layout #108
* [x] Add developer docs #109

Later possible extensions:

* Overview of models that the workflow can build (including links to pre-builts)
* Various auto-built documentation on the components, data sources, models, ...

**Comment by sjpfenninger** [comment]
We can use sphinx with markdown: https://www.sphinx-doc.org/en/master/usage/markdown.html

**Comment by sjpfenninger** [comment]
This is a meta-issue that tracks all the initial setup for the docs, so should remain open?

**Comment by timtroendle** [comment]
The four issues mentioned above have been covered and in addition several more (#159, #156, #68, #165).
