### ISSUE TITLE
Get demand for "other" industry and process it

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/euro-calliope#309]
Create rules/workflow to output demands for all industries without individual processing at a national level:

**TODO:**

- [ ] Identify which industry sectors have no specific processing steps.
- [ ]  Get demands for key final energy carriers (methane, diesel, electricity) and end uses (space heat).
- [ ] Produce the final file by combining the demands above 

This issue is linked to https://github.com/calliope-project/euro-calliope/issues/102
