### ISSUE TITLE
Update steel industry demand and process it

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/euro-calliope#310]
Create rules/workflow to output industry demand at a national level:

**TODO:**

- [x] Get demand for steel industry from JRC-IDEES
- [x]  Replace energy consumption in reducing iron and blast furnaces with pre-computed hydrogen and electricity requirements for direct reduction of iron (DRI)
- [x] update energy consumption for processing steel based on electric arc processes applied to all steel, not only recycled steel

This issue is linked to https://github.com/calliope-project/euro-calliope/issues/102

**Comment by irm-codebase** [comment]
Closed by #340
